### ISSUE TITLE
Supervise the store

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#143]
It's about time we integrate `marketstor` as a "micro-daemon" spawned as part of [`pikerd`](https://github.com/pikers/piker/blob/master/piker/cli/__init__.py#L35) startup. More on `pikerd` re-design at end.

The current command I would expect to use is something like:
```
sudo docker run -v "/home/<user>/.config/piker/mkts.yml:/etc/mkts.yml" -v "/home/<user>/.config/piker/marketstore:/data" -p 5993:5993 alpacamarkets/marketstore:latest
```
which gets us
- latest released container
-  running with the data dir mapped to the `piker` user config dir
- with a `mks.yaml` config also in that same dir

The config we've been using is currently:
```yaml
# mount this config using:
# sudo docker run --mount type=bind,source="<path-to-piker>/piker/piker/data/configs",target="/etc" \
# -i -p 5993:5993 alpacamarkets/marketstore:latest
root_directory: data
listen_port: 5993
grpc_listen_port: 5995
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
stale_threshold: 5
enable_add: true
enable_remove: false

triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
        # filter: "nasdaq"
        destinations:
            - 1Min
            - 5Min
            - 15Min
            - 1H
            - 1D

  - module: stream.so
    on: '*/*/*'
    # config:
    #     filter: "nasdaq"
```

This will need to be updated as features from #142 land.

I propose the following a spawning and supervision:
- creat a supervising actor under `pikerd` and have it use `docker-py` to (pull and) run the container
- make some kind of sync mechanism to let other actors know the db can be used freely once up and running
- make this supervisor stream in logs from the container and and log them using piker logging where possible
- if there is a critical failure (container outright crashes) we should have come facility for respawn

It would further be great to get some of these container input params specced out in a piker config file.

In terms of a `pikerd` root service, we need to probably rejig this to use `tractor`'s new [implicit runtime stuff](https://github.com/goodboy/tractor/pull/185) as well as anticipate being the root process that launches UI components (Qt) in a child.
