### ISSUE TITLE
the boss, `config.toml`

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#221]
i'm thinking we might as well have a top level config file for users to choose and tweak a lot of optional/variable settings we starting to acquire.

Some options i can think of off-hand,

```toml
[allocation.default]
size_units = 'currency'
limit = 5e3
slots = 4

[allocation.options]
size_units = 'units'
limit = 10
slots = 1

[allocation.peeneez]
size_units = 'percent_of_port'
limit = 20
slots = 6

[style]
colorscheme = 'default'

[tractor]
port = 6116

[ui]
update_throttle = 60  # Hz
```

opinions welcome obvsly.
